### ISSUE TITLE
Barrels and Chests spawn in halls

### ISSUE THREAD

**Issue by tylervipond** [tylervipond/apprentice#50]
Sometimes a barrel or chest will spawn in a hallway. This is because if the room it spawns in is circular, the test to find out whether there's an available floor tile doesn't take into account the fact that the rect is now smaller (and square) as it now holds a circle.

One possible solve is to update the x,y values of the rect when it's made into a circle.

**Comment by alexeagleson** [comment]
Encountered this as well
